<?php
return [
  "id" => 1,
  "article_no" => "834 000 139",
  "name" => "AMTRON®",
  "byline" => "Compact",
  "description" => "",
  "descriptionFull" => [
    'Ladeleistungen von 3,7 kW (einphasig) bis zu 11 kW (dreiphasig)',
    'Die Ladeleistung ist von einer Elektrofachkraft am Gerät einstellbar', 
    'Fest angeschlossenes Ladekabel Typ 2, Länge 5 m',
    'Anzeige des Betriebszustandes dank  dem LED-Infofeld',
    'Keine Autorisierung notwendig',
    'Potentialfreier Kontakt (Autorisierung / Rundsteuersignal)',
    'Einfaches Lastmanagement (0/6/8/10/13A)',
    'Temperaturüberwachung',
    'DC-Fehlerstromüberwachung > 6mA',
    'Installation von Personenschutzschalter (FI) Typ A und Leistungsschutzschalter (LS) Typ C muss bauseits erfolgen',
    'Schutzart IP54',
  ],
  "isVisible" => true,
  "hasVariation" => false,
  "hasCloud" => false,
  "price" => 790.00,
  "image" => "",
  "images" => [
    "mennekes-amtron-1.jpg",
    "mennekes-amtron-2.jpg",
    "mennekes-amtron-3.jpg",
    "mennekes-amtron-4.jpg",
    "mennekes-amtron-5.jpg",
    "mennekes-1.jpg",
  ],
  "match" => 1,
  "props" => [
    "solar" => [-1],
    "stat_load_mgmt" => [0,1],
    "dyn_load_mgmt" => [-1],
    "charge_cable" => [1],
    "charge_plug" =>[-1],
    "power_11" => [1],
    "power_22" => [-1],
    "cloud_private" => [-1],
    "cloud_public" => [-1],
    "cloud_data" => [-1],
    "cloud_connect" => [-1],
    "cloud_pay" => [-1],
    "accessory_pedestal" => [0,1],
    "accessory_rfid" => [-1],
    "accessory_cable" => [0,1],
    "package_abo" => [0,1],
    "package_plus" => [0,1],
    "package_combi" => [0,1],
    "installation" => [0,1],
    "communication" => [-1],
  ],
  "file_options" => "default"
];