<?php

return [
  "id" => 23,
  "article_no" => "834 301 109",
  "name" => "MENNEKES Ladesäule Basic",
  "byline" => "2x22kW",
  "descriptionFull" => [
    '2 Ladepanels mit je 1 Steckdose Typ 2 für 11 kW bzw. 22 kW',
    'Ladeleistung bis 22 kW (dreiphasig) mit automatischer Leistungsanpassung auf 11 kW (dreiphasig)',
    'Autorisierung über Schlüssel oder externer Signalgeber',
    'Entriegelungsfunktion bei Stromausfall',
    'FI-Personenschutz 40A, 4P, Typ B (allstromsensitiv) integriert',
    'Integrierter LS-Schalter 32A und LS-Schalter 16A',
    'Befestigungs- und Kontaktiereinheit (BKE) für EHZ Zäher vorbereitet, ohne Zähler',
    'Manuelles fest definierbares Lastmanagement bei 22 kW-Version definierbar',
    'Gehäuse: Stahlblech, verzinkt, pulverbeschichtet',
    'Ausführung in Schwarz (SW) RAL9005; lieferbar auch in den Farben, Silber und Gelb',
    'Abmessung: 1300 x 348 x 250 mm (HxBxT)',
    'Schutzart IP44',
  ],
  "group" => 'mennekes-pillar',
  "isVisible" => false,
  "hasVariation" => true,
  "hasCloud" => true,
  "price" => 9626.00,
  "charge_cable" => -1,
  "charge_plug" => true,
  "installation_cable" => -1,
  "communication_gsm" => false,
  "communication_ethernet" => false,
  "communication_wifi" => false,
  "vandalism" => true,
  "power_11" => false,
  "power_22" => true,
  "mid" => -1,
  "images" => [
    "mennekes-basic-1.jpg",
    "mennekes-1.jpg",
    "mennekes-2.jpg",
  ],
  "match" => 1,
  "props" => [
    "solar" => [0,1],
    "stat_load_mgmt" => [0,1],
    "dyn_load_mgmt" => [-1],
    "charge_cable" => [-1],
    "charge_plug" => [1],
    "power_11" => [-1],
    "power_22" => [0,1],
    "cloud_private" => [0,1],
    "cloud_public" => [0,1],
    "cloud_data" => [0,1],
    "cloud_connect" => [0,1],
    "cloud_pay" => [0,1],
    "accessory_pedestal" => [-1],
    "accessory_rfid" => [0,1],
    "accessory_cable" => [0,1],
    "package_abo" => [0,1],
    "package_plus" => [0,1],
    "package_combi" => [0,1],
    "installation" => [0,1],
    "communication" => [0,1],
    "communication_ethernet" => [-1],
    "communication_wifi" => [-1],
    "communication_gsm" => [-1],
    "installation_cable" => [0,1],
    "installation_single_line" => [0,1],
    "mid" => [0,1],
    "setup_pillar" => [1],
    "setup_wall" => [-1],
    "vandalism" => [0,1],
  ],
  "file_options" => "default"
];