<?php
return [
  "id" => 10,
  "article_no" => "834 005 049",
  "name" => "AMTRON Professional+",
  "byline" => "R C2 22kW",
  "slave_id" => 12,
  "descriptionFull" => [
    'Integriertes Funk-Modem (Mico-SIM) für die Mobilfunkstandards 4G (LTE) 3G (UMTS) und 2G (GSM)',
    'Kompatibel mit OCPP 1.5 und 1.6.',
    'Fest angeschlossenes Ladekabel, Länge 7,5m mit Ladekupplung Typ 2 für Mode 3 Ladung',
    'Ladeleistungen bis zu 7,4 kW (1ph) / 22kW (3ph)',
    'Autorisierung via RFID-Karte mit Backend mobilecharge',
    'Vernetzung (Master/Satelit) über LAN',
    'Statusinformationen per LED-Infofeld',
    'Entriegelungsfunktion bei Stromausfall',
    'Von aussen ablesbarer zertifizierter MID Energiezähler',
    'Integrierter Fehlerstromschutzschalter FI 40A Typ A Leitungsschutzschalter LS 32A Typ C',
    'Fehlerstromüberwachung > 6mA',
    'Schutzart IP 44',
  ],
  "group" => "mennekes",
  "isVisible" => false,
  "hasVariation" => true,
  "hasCloud" => true,
  "price" => 2290.00,
  "charge_cable" => true,
  "charge_plug" => false,
  "installation_cable" => true,
  "communication_gsm" => true,
  "communication_ethernet" => true,
  "communication_wifi" => -1,
  "mid" => -1,
  "vandalism" => -1,
  "power_11" => -1,
  "power_22" => -1,
  "images" => [
    "mennekes-amtron-professional-1.jpg",
    "mennekes-amtron-professional-2.jpg",
    "mennekes-amtron-professional-3.jpg",
  ],
  "match" => 1,
  "props" => [
    "solar" => [0,1],
    "stat_load_mgmt" => [0,1],
    "dyn_load_mgmt" => [0,1],
    "charge_cable" => [0,1],
    "charge_plug" => [-1],
    "power_11" => [0,1],
    "power_22" => [0,1],
    "cloud_private" => [0,1],
    "cloud_public" => [0,1],
    "cloud_data" => [0,1],
    "cloud_connect" => [0,1],
    "cloud_pay" => [0,1],
    "accessory_pedestal" => [0,1],
    "accessory_rfid" => [0,1],
    "accessory_cable" => [0,1],
    "package_abo" => [0,1],
    "package_plus" => [0,1],
    "package_combi" => [0,1],
    "installation" => [0,1],
    "communication" => [0,1],
    "communication_ethernet" => [1],
    "communication_gsm" => [1],
    "communication_wifi" => [-1],
    "installation_cable" => [0],
    "installation_single_line" => [0,1],
    "mid" => [0,1],
    "setup_pillar" => [-1],
    "setup_wall" => [1],
    "vandalism" => [-1],
  ],
  "file_options" => "mennekes"
];