<?php

return [
  "id" => 15,
  "article_no" => "G-PC1-S5B-Y20",
  "name" => "ETREL INCH Wallbox PRO",
  "byline" => "C2 22 R DC LAN+WiFi",
  "descriptionFull" => [
    'ETREL INCH PRO Wallbox verbindet modernes Design mit grosser Intelligenz',
    'LCD-Farbbildschirm, Grösse 3,5 Zoll (320x240)',
    'Max. Ladeleistung 1x 22kW (32A/3p)',
    'Fest angeschlossenes Ladekabel (C2), Länge 7 Meter mit Ladekupplung Typ 2 für Mode 3 Ladung',
    'Autorisierung mit RFID-Karten, PIN-Code,  QR Code und SMS',
    'Kommunikation über Ethernet / WiFi / GSM',
    'Modbus TCP oder OCPP-Protokoll',
    'Mit intelligente Autonomie-Funktion',
    'Inklusive Clustering-Unterstützung bis 15 Ladestationen',
    'Schutzart IP54',
    'Integrierte DC-Fehlererkennung mit Personenschutz FI 40A Typ A (R)', 
    'LS muss bauseits installiert werden',
  ],
  "group" => "etrel",
  "isVisible" => false,
  "hasVariation" => true,
  "hasCloud" => true,
  "price" => 1960.00,
  "charge_cable" => true,
  "charge_plug" => false,
  "installation_cable" => -1,
  "communication_gsm" => true,
  "communication_ethernet" => true,
  "communication_wifi" => true,
  "mid" => false,
  "vandalism" => -1,
  "power_11" => -1,
  "power_22" => -1,
  "images" => [
    "etrel-inch-1.jpg",
    "etrel-inch-2.jpg",
    "etrel-inch-3.jpg",
    "etrel-inch-4.jpg",
  ],
  "match" => 1,
  "props" => [
    "solar" => [0,1],
    "stat_load_mgmt" => [0,1],
    "dyn_load_mgmt" => [0,1],
    "charge_cable" => [0,1],
    "charge_plug" => [-1],
    "power_11" => [0,1],
    "power_22" => [0,1],
    "cloud_private" => [0,1],
    "cloud_public" => [0,1],
    "cloud_data" => [0,1],
    "cloud_connect" => [0,1],
    "cloud_pay" => [0,1],
    "accessory_pedestal" => [0,1],
    "accessory_rfid" => [0,1],
    "accessory_cable" => [0,1],
    "package_abo" => [0,1],
    "package_plus" => [0,1],
    "package_combi" => [0,1],
    "installation" => [0,1],
    "communication" => [0,1],
    "communication_ethernet" => [1],
    "communication_wifi" => [1],
    "communication_gsm" => [1],
    "installation_cable" => [-1],
    "installation_single_line" => [0,1],
    "mid" => [0,1],
    "setup_pillar" => [-1],
    "setup_wall" => [1],
    "vandalism" => [-1],
  ],
  "file_options" => "etrel"
];