<?php
return [
  "id" => 5,
  "article_no" => "G-HB1-YBD-Y20",
  "name" => "ETREL INCH Home Wallbox",
  "byline" => "T2 22 E DC LAN+WiFi",
  "description" => "",
  "descriptionFull" => [
    'ETREL INCH Home Wallbox verbindet modernes Design mit grosser Intelligenz',
    'Aluminiumgehäuse mit Polycarbonat Lexan Abdeckung, dunkelgrau',
    'LCD-Farbbildschirm, Grösse 3,5 Zoll (320x240)',
    'Max. Ladeleistung 1x 22kW (32A/3p)',
    'Die Ladeleistung ist von einer Elektrofachkraft am Gerät einstellbar',
    'Mit Ladesteckdose Typ 2 (T2) für Mode 3 Ladung',
    'Autorisierung mit Dauerladung und Code',
    'Kommunikation über Ethernet / WiFi / Modbus', 
    'TCP oder OCPP-Protokoll',
    'Ideal für den Einsatz in PV-Anlagen oder Backend mobilecharge',
    'Mit intelligente Autonomie-Funktion',
    'Inklusive Lademanagement für 2 Ladestationen',
    'Schutzart IP54',
    'Zertifizierter MID Energiezähler',
    'Integrierte DC-Fehlererkennung (E)',
    'FI und LS muss bauseits installiert werden',
  ],
  "isVisible" => false,
  "hasVariation" => true,
  "hasCloud" => true,
  "price" => 1450.00,
  "charge_cable" => false,
  "charge_plug" => true,
  "cloud_private" => true,
  "cloud_public" => true,
  "image" => "",
  "images" => [
    "etrel-inch-1.jpg",
    "etrel-inch-2.jpg",
    "etrel-inch-3.jpg",
    "etrel-inch-4.jpg",
  ],
  "match" => 1,
  "props" => [
    "solar" => [0,1],
    "stat_load_mgmt" => [0,1],
    "dyn_load_mgmt" => [0,1],
    "charge_cable" => [0,1],
    "charge_plug" => [0,1],
    "power_11" => [0,1],
    "power_22" => [0,1],
    "cloud_private" => [0,1],
    "cloud_public" => [0,1],
    "cloud_data" => [0,1],
    "cloud_connect" => [0,1],
    "cloud_pay" => [0,1],
    "accessory_pedestal" => [0,1],
    "accessory_rfid" => [0,1],
    "accessory_cable" => [0,1],
    "package_abo" => [0,1],
    "package_plus" => [0,1],
    "package_combi" => [0,1],
    "installation" => [0,1],
    "communication" => [0,1],
  ],
  "file_options" => "etrel"
];