<?php

return [
  "id" => 19,
  "article_no" => "834 300 149",
  "name" => "MENNEKES AMEDIO Pro+",
  "byline" => "R 22",
  "descriptionFull" => [
    'Integriertes Modem (Micro-SIM) für die Mobilfunkstandards 4G (LTE) 3G (UMTS) und 2G (GSM)',
    'Kompatibel mit OCPP 1.5 und 1.6',
    'Ladeleistungen bis zu 7,4 kW (1ph) / 22kW (3ph) je Ladesteckdose',
    'Autorisierung via RFID-Karte (MIFARE classic und MIFARE DESFire)',
    'Vernetzung (Master/Satelit) über LAN',
    'Lokales Lastmanagement',
    'Statusinformationen per LED-Infofeld',
    'Entriegelungsfunktion bei Stromausfall',
    'Von aussen ablesbarer und zertifizierter  MID Energiezähler',
    'Integrierter Fehlerstromschutzschalter Typ A, Leitungsschutzschalter, DC-Fehlerstromüberwachung > 6mA',
    'Nennstrom 63A, Schutzart IP 54',
    'Gehäuse aus Schwarzblech, verzinkt und pulverbeschichtet. Decke aus Kunststoff',
    'Anschlussklemmen 5x2x35mm2',
    'Abmessungen HxBxT: 1362 x 352 x 252mm',
    'Anschlussfertig verdrahtet',
  ],
  "group" => 'mennekes-pillar',
  "isVisible" => true,
  "hasVariation" => true,
  "hasCloud" => true,
  "price" => 6450.00,
  "charge_cable" => -1,
  "charge_plug" => true,
  "installation_cable" => -1,
  "communication_gsm" => true,
  "communication_ethernet" => true,
  "communication_wifi" => -1,
  "vandalism" => false,
  "power_11" => true,
  "power_22" => true,
  "mid" => -1,
  "images" => [
    "mennekes-amedio-1.jpg",
    "mennekes-1.jpg",
    "mennekes-2.jpg",
  ],
  "match" => 1,
  "props" => [
    "solar" => [0,1],
    "stat_load_mgmt" => [0,1],
    "dyn_load_mgmt" => [0,1],
    "charge_cable" => [-1],
    "charge_plug" => [1],
    "power_11" => [0,1],
    "power_22" => [0,1],
    "cloud_private" => [0,1],
    "cloud_public" => [0,1],
    "cloud_data" => [0,1],
    "cloud_connect" => [0,1],
    "cloud_pay" => [0,1],
    "accessory_pedestal" => [-1],
    "accessory_rfid" => [0,1],
    "accessory_cable" => [0,1],
    "package_abo" => [0,1],
    "package_plus" => [0,1],
    "package_combi" => [0,1],
    "installation" => [0,1],
    "communication" => [0,1],
    "communication_ethernet" => [1],
    "communication_wifi" => [-1],
    "communication_gsm" => [1],
    "installation_cable" => [0,1],
    "installation_single_line" => [0,1],
    "mid" => [0,1],
    "setup_pillar" => [1],
    "setup_wall" => [-1],
    "vandalism" => [-1],
  ],
  "file_options" => "mennekes"
];